cinema/urls.py
from django.urls import path

from cinema import views

app_name = "cinema"
urlpatterns = [
    path(route="", view=views.film_list_view, name="film_list"),
    path(
        route="search/",
        view=views.search_view,
        name="search",
    ),
    path(
        route="<slug:genre_slug>/",
        view=views.film_list_view,
        name="film_list_by_genre",
    ),
    path(
        route="films/<slug:slug>/",
        view=views.film_detail_view,
        name="film_detail",
    ),
    path(
        route="people/<person_role>/",
        view=views.people_list_view,
        name="people_list",
    ),
    path(
        route="person/<int:person_id>",
        view=views.person_detail_view,
        name="person_detail",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("accounts/", include("account.urls")),
    path("api/v1/", include("api.urls")),
    path("", include("cinema.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

cinema/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField


class Genre(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=50, unique=True, null=True, blank=True)

    class Meta:
        ordering = ("name",)
        indexes = (models.Index(fields=("name",)),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("cinema:film_list_by_genre", args=(self.slug,))

    def __str__(self) -> str:
        return self.name


class PersonQuerySet(models.QuerySet):
    def is_actor(self):
        return self.filter(starred_films__isnull=False).distinct()

    def is_director(self):
        return self.filter(directed_films__isnull=False).distinct()


class Person(models.Model):
    GENDER_CHOICES = [
        ("M", "Male"),
        ("F", "Female"),
    ]

    image = models.ImageField(
        upload_to="people/%Y/%m/%d/", null=True, blank=True, default=None
    )
    name = models.CharField(max_length=60)
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, null=True, blank=True
    )

    objects = PersonQuerySet.as_manager()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "People"


class Film(models.Model):
    slug = models.SlugField(max_length=255, unique=True)
    poster = models.ImageField(
        upload_to="films/%Y/%m/%d/", null=True, blank=True, default=None
    )
    title = models.CharField(max_length=100)
    premiere = models.DateField()
    country = CountryField(blank=True)
    duration = models.IntegerField(null=True, blank=True)
    rating = models.FloatField(editable=False, blank=True, default=0.0)
    profit = models.BigIntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    genre = models.ForeignKey(
        Genre, related_name="films", on_delete=models.SET_NULL, null=True
    )
    directors = models.ManyToManyField(
        Person, related_name="directed_films", blank=True
    )
    actors = models.ManyToManyField(
        Person, related_name="starred_films", blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("cinema:film_detail", kwargs={"slug": self.slug})

    def __str__(self) -> str:
        return self.title


class Vote(models.Model):
    film = models.ForeignKey(
        Film, related_name="votes", on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    rating = models.SmallIntegerField(editable=False)

    def __str__(self) -> str:
        return f"Film_{self.film.id}: {self.rating} from User_{self.user.id}"

    class Meta:
        unique_together = (
            "film",
            "user",
        )

cinema/views.py
import imdb.services as imdb
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Avg, Q
from django.http import (
    Http404,
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from cinema.models import Film, Genre, Person, Vote


def film_list_view(request, genre_slug=None):
    """List all the movies or filter movies by a given genre."""

    genre = None
    genres = Genre.objects.all()
    films = Film.objects.all().select_related("genre")

    order_by_value = request.GET.get("order_by", "rating")

    if genre_slug is not None:
        genre = get_object_or_404(Genre, slug=genre_slug)
        films = films.filter(genre=genre)

    order_by_fields = {
        "rating": "-rating",
        "title": "title",
        "premiere": "-premiere",
    }
    try:
        films = films.order_by(order_by_fields[order_by_value])
    except KeyError:
        return HttpResponseRedirect(reverse("cinema:film_list"))

    paginator = Paginator(object_list=films, per_page=6)
    page = request.GET.get("page")

    try:
        films = paginator.page(number=page)
    except PageNotAnInteger:
        films = paginator.page(number=1)
    except EmptyPage:
        if request.is_ajax():
            # If AJAX request and page out of range return an empty page
            return HttpResponse("")
        # If page out of range return the last page of results
        films = paginator.page(number=paginator.num_pages)

    if request.is_ajax():
        return render(
            request=request,
            template_name="cinema/film_list.html",
            context={"films": films},
        )

    return render(
        request=request,
        template_name="cinema/cinema.html",
        context={
            "genre": genre,
            "genres": genres,
            "films": films,
        },
    )


def film_detail_view(request, slug):
    if request.method == "POST":
        if request.user.is_authenticated:
            value = int(request.POST["vote"])

            if value > 10 or value < 1:
                return JsonResponse(
                    data={"message": "Unvalid vote value!"}, status=400
                )
            try:
                film = Film.objects.get(slug=slug)
            except (ObjectDoesNotExist, MultipleObjectsReturned):
                return JsonResponse(
                    data={
                        "message": "Impossible to get the film by given slug!"
                    },
                    status=400,
                )

            Vote.objects.update_or_create(
                user=request.user,
                film=film,
                defaults={"rating": value},
            )
            # update film overall rating based on users votes
            film.rating = film.votes.aggregate(Avg("rating"))["rating__avg"]
            film.save()

            return JsonResponse(
                data={"overall_rating": film.rating},
                status=200,
            )
        else:
            return JsonResponse(
                {"message": "You're not authenticated!"}, status=400
            )
    else:
        try:
            film = Film.objects.get(slug=slug)
        except ObjectDoesNotExist:
            raise Http404("Film is not found!")
        except MultipleObjectsReturned:
            raise Http404("several records with same IDs were found!")

        if request.user.is_authenticated:
            try:
                vote = Vote.objects.get(
                    film__slug=slug, user__id=request.user.id
                ).rating
            except (ObjectDoesNotExist, MultipleObjectsReturned):
                vote = 0
        else:
            vote = 0

        imdb_rating = imdb.get_movie_rating_by_title(title=film.title)

    return render(
        request,
        "cinema/film_detail.html",
        {"film": film, "vote": vote, "imdb_rating": imdb_rating},
    )


def people_list_view(request, person_role):
    if person_role not in ("actors", "directors"):
        raise Http404()

    if person_role == "actors":
        person_list = Person.objects.is_actor().filter().order_by("name")
    elif person_role == "directors":
        person_list = Person.objects.is_director().filter().order_by("name")

    paginator = Paginator(object_list=person_list, per_page=6)
    page = request.GET.get("page")

    try:
        person_list = paginator.page(number=page)
    except PageNotAnInteger:
        person_list = paginator.page(number=1)
    except EmptyPage:
        if request.is_ajax():
            # If AJAX request and page out of range return an empty page
            return HttpResponse("")
        # If page out of range return the last page of results
        person_list = paginator.page(number=paginator.num_pages)

    if request.is_ajax():
        return render(
            request=request,
            template_name="cinema/person_list.html",
            context={"person_list": person_list},
        )
    return render(
        request=request,
        template_name="cinema/actor_director_list.html",
        context={"section": person_role, "person_list": person_list},
    )


def person_detail_view(request, person_id):
    try:
        person = Person.objects.get(id=person_id)
    except ObjectDoesNotExist:
        raise Http404("Person not found.")
    except MultipleObjectsReturned:
        raise Http404("Multiple people with the same ID found.")

    actor_films = person.starred_films.order_by("-rating")
    director_films = person.directed_films.order_by("-rating")

    return render(
        request=request,
        template_name="cinema/person_detail.html",
        context={
            "person": person,
            "actor_films": actor_films,
            "director_films": director_films,
        },
    )


def search_view(request):
    query = request.GET.get("search_line", "").strip()

    if query:
        films = Film.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query)
        )
        people = Person.objects.filter(name__icontains=query)
    else:
        films = Film.objects.all()
        people = Person.objects.all()

    return render(
        request=request,
        template_name="cinema/search.html",
        context={
            "people": people,
            "films": films,
        },
    )

templates/cinema/actor_director_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ section.capitalize }}{% endblock %}

{% block content %}
  <div class="my-3 p-3 w-75 mx-auto">
    <div class="d-flex bg-dark justify-content-between align-items-center text-white rounded">
      <p><h3 class="my-1">{{ section.capitalize }}</h3></p>
    </div>
    
    <div id="actor-director-list" class="row row-cols-1 row-cols-md-3 mt-3">
      {% include 'cinema/person_list.html' with person_list=person_list only %}
    </div>
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;
  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 300;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
        if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#actor-director-list').append(data);
        }
      });
    }
  });
{% endblock domready %}

templates/cinema/actor_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Actors{% endblock %}

{% block content %}
  <div class="my-3 p-3 w-75 mx-auto">
    <div class="d-flex bg-dark justify-content-between align-items-center text-white rounded">
      <p><h3 class="my-1">Actors</h3></p>
    </div>
    
    <div id="actors-list" class="row row-cols-1 row-cols-md-3 mt-3">
      {% include 'cinema/person_list.html' with person_list=actors only %}
    </div>
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;
  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 300;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
        if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#actors-list').append(data);
        }
      });
    }
  });
{% endblock domready %}

templates/cinema/cinema.html
{% extends 'base.html' %}
{% load static cinemas_extra %}


{% block title %}{% if genre %}{{ genre.name }}{% else %}Movies{% endif %}{% endblock %}

{% block content %}
<div class="my-3 p-3 w-75 mx-auto">
  <div class="d-flex bg-dark justify-content-between align-items-center text-white rounded">
    <p><h3 class="my-1">{% if genre %}{{ genre.name }}{% endif %} Movies</h3></p>
  </div>

  <div class="row gx-0 pt-3 flex-nowrap">
    <div id="sidebar" class="col-auto col-md-3 col-xl-2 pe-sm-2 px-0">
      <div class="d-flex flex-column align-items-center px-2 text-white bg-dark rounded">
        <ul class="list-group list-group-flush">
          <a href="{% url "cinema:film_list"%}" class="text-decoration-none text-center">
            <li class="list-group-item list-group-item-action rounded m-2 px-2 py-0{% if not genre %} selected" aria-current="true"{% else %}"{% endif %}>
              <span class="fs-5">All</span> 
            </li>
          </a>
          {% for g in genres %}
            <a href="{{ g.get_absolute_url }}" class="text-decoration-none text-center">
              <li class="list-group-item list-group-item-action rounded m-2 px-2 py-0{% if genre.slug == g.slug %} selected" aria-current="true"{% else %}"{% endif %}>
                <span class="fs-5">{{ g.name }}</span>    
              </li>
            </a>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="col pb-3 ms-2">
      <div class="d-flex bg-dark justify-content-between align-items-center mb-2 px-2 text-white rounded">
        <a class="order-by-option text-decoration-none" id="rating" href="#">
          <h5 class="my-1">Order by rating</h5>
        </a>
        <a class="order-by-option text-decoration-none" id="title" href="#">
          <h5 class="my-1">Order by title</h5>
        </a>
        <a class="order-by-option text-decoration-none" id="premiere" href="#">
          <h5 class="my-1">Order by premiere</h5>
        </a>
      </div>

      <div id="films-list" class="d-grid gap-1">
        {% include 'cinema/film_list.html' with films=films only%}
        </div>
    </div>
  </div>
</div>
{% endblock %}

{% block domready %}
  $(".order-by-option").on('click', function(e) {
    e.preventDefault();

    const order_by = $(this).attr("id");
    console.log(order_by);
    $.ajax({
      type: "GET",
      url: window.location.href,
      data: {
        'order_by': order_by,
      },
      success: function (response) {
        $('#films-list').html(response);
      }
    });
  });

  var page = 1;
  var empty_page = false;
  var block_request = false;
  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 300;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
        if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#films-list').append(data);
        }
      });
    }
  });
{% endblock domready %}

templates/cinema/director_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Directors{% endblock %}

{% block content %}
  <div class="my-3 p-3 w-75 mx-auto">
    <div class="d-flex bg-dark justify-content-between align-items-center text-white rounded">
      <p><h3 class="my-1">Directors</h3></p> 
    </div>

    <div id="directors-list" class="row row-cols-1 row-cols-md-3 mt-3">
      {% include 'cinema/person_list.html' with person_list=directors only %}
    </div>
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;
  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 300;
    if($(window).scrollTop() > margin && empty_page == false && block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
        if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#directors-list').append(data);
        }
      });
    }
  });
{% endblock domready %}

templates/cinema/film_detail.html
{% extends 'base.html' %}
{% load static cinemas_extra %}

{% block title %}{{ film.title }}{% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-center my-3 p-3 bg-body rounded shadow w-85 mx-auto">
  <div class="d-grid gap-1" style="grid-template-columns: 230px auto">
    <div class="d-flex justify-content-center">
      {% if film.poster %}
        <a href="{{ film.poster.url }}">
          <img class="rounded" src="{{ film.poster.url }}" style="max-width: 100%; height: auto;">
        </a>
      {% else %}
        <img class="rounded" src="{% static 'images/movie_question.png' %}" height="300" width="200">
      {% endif %}
    </div>
    <div class="px-1">
      <div>
        <h4>
          {{ film.title }}
          <img src="{% if film.country %}{{ film.country.flag }}{% endif %}" />
        </h4>
        <p class="fs-6">{% if film.description %}{{ film.description }}{% endif %}</p>
      </div>
      <hr>
      <div class="row">
        <div class="col">
          <div class="d-flex">
            <h6><b>Genre:</b></h6>
            <h6 class="mx-2"><a href="{{ film.genre.get_absolute_url  }}">{% if film.genre %}{{ film.genre.name }}{% endif %}</a></h6>
          </div>
          <div class="d-flex">
            <h6><b>World premiere:</b></h6>
            <h6 class="mx-2">{{ film.premiere }}</h6>
          </div>
          <div class="d-flex">
            <h6><b>Running time:</b></h6>
            <h6 class="mx-2">
              {% if film.duration %}
                  {{ film.duration|pretty_time }}
              {% endif %}
            </h6>
          </div>
          <div class="d-flex">
            <h6><b>Box office:</b></h6>
            <h6 class="mx-2">
              {% if film.profit %}
                {{ film.profit|pretty_profit }}
              {% endif %} 
            </h6>
          </div>
        </div>
        <div class="col">
          {% if imdb_rating %}
            <div class="d-flex">
              <h6><b>IMDB rating:</b></h6>
              <h6 class="mx-2">{{ imdb_rating }}</h6>
            </div>
          {% endif %}
          <div id="film_rating_container"
                style="display: {% if film.rating == 0 %}none{% else %}flex{% endif %}">
              <h6><b>Rating:</b></h6>
              <h6 class="mx-2" id="film_rating">{{ film.rating }}</h6>
          </div>
          <div>
            <h6><b>Choose your rating:</b></h6>
            <div>
              {% for index in 1|range:11 %}
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#D4D4D4"
                    class="star bi bi-star-fill" viewBox="0 0 16 16" onclick="vote({{ index }})">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
              </svg>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col">
          <h6><b>Actors:</b></h6>
          <div>
            <p>
              {% for film_actor in film.actors.all %}
                <a href="{% url 'cinema:person_detail' film_actor.id %}">{{ film_actor.name }}</a>
                {{ forloop.last|yesno:",&#44;"|safe }}
              {% endfor %}
            </p>
          </div>
        </div>
        <div class="col">
          {% with film_directors=film.directors.all %}
          <h6><b>Director{{ film_directors|pluralize }}:</b></h6>
          <div>
            <p>
              {% for film_director in film_directors %}
                <a href="{% url 'cinema:person_detail' film_director.id %}">{{ film_director.name }}</a>
                {{ forloop.last|yesno:",&#44;"|safe }}
              {% endfor %}
            </p>
          {% endwith %} 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  let vote_rating = {{ vote }};
  star_fill(vote_rating);

  function vote(value) {
    $.ajax({
        type: "POST",
        url: "{% url 'cinema:film_detail' film.slug %}",
        data: {
          'csrfmiddlewaretoken': Cookies.get('csrftoken'),
          'vote': value
        },
        dataType: 'json'
    })
    .done(function (response) {
      $("#film_rating").html(response['overall_rating'])
      $("#film_rating_container").css('display', 'flex');
      vote_rating = value;
    })
  }

  $('.star').css({cursor: 'pointer'});

  $('.star').hover(function () {
    $(this).parent().children('.star').css({fill: '#D4D4D4'});
    $(this).prevAll().each(function () {
        $(this).css({fill: 'orange'});
    });
    $(this).css({fill: 'orange'});
  }, () => star_fill(vote_rating));

  function star_fill(value) {
    let stars = $('.star').parent().children('.star');
    stars.each(function (index) {
      if (index < value) {
        this.style.fill = 'orange'
      } else {
        this.style.fill = '#D4D4D4'
      }
    });
  }
</script>
{% endblock %}

templates/cinema/film_list.html
{% load static cinemas_extra thumbnail %}

{% for film in films %}
<div class="card border-dark mb-1 shadow" style="/*max-width: 540px;*/">
  <div class="row g-0">
    <div class="col-md-3">
      <img src="{% if film.poster %}{{ film.poster.url }}{% else %}{% static "images/movie_question.png" %}{% endif %}" class="img-fluid rounded-start p-1" height="200" width="143">
    </div>
    <div class="col-md-8">
      <div class="card-body ps-0">
        <h5 class="card-title">
          <div class="d-flex justify-content-between">
            <a href="{{ film.get_absolute_url }}">
              {{ film.title }}
            </a>
            {% if film.rating != 0 %}
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="orange" 
                  class="bi bi-star-fill" viewBox="0 0 16 16">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
                {{ film.rating }}
              </div>
            {% endif %}
          </div>
        </h5>
        {% if film.premiere %}
          <p class="card-text mb-0"><b>Premiere:</b> {{ film.premiere }}</p>
        {% endif %}
        {% if film.country %}
          <p class="card-text mb-0"><b>Country:</b> <img src="{{ film.country.flag }}" /></p>
        {% endif %}
        {% if film.genre %}
          <p class="card-text mb-0"><b>Genre:</b> <a href="{{ film.genre.get_absolute_url }}">{{ film.genre }}</a></p>
        {% endif %}
        <p class="card-text mt-1">{{ film.description|truncatewords:25 }}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

templates/cinema/person_detail.html
{% extends 'base.html' %}
{% load static cinemas_extra thumbnail %}

{% block title %}{{ person.name }}{% endblock %}

{% block content %}
  <div class="d-flex flex-column align-items-center my-3 p-3 bg-body rounded shadow w-75 mx-auto">
    <div class="row">
      <div class="col">
        {% if person.image %}
          {% thumbnail person.image 250x250 crop="100%" as im %}
          <img src="{{ im.url }}" class="rounded">
        {% else %}
          <img src="{% static "images/man_question.png" %}" class="card-top">
        {% endif %}
      </div>
      <div class="col">
        <h3>{{ person.name }}</h3>
        <div class="d-flex flex-column justify-content-center" style="height: 80%">
          <p><b>Birthday: </b> {% if person.birthday %}{{ person.birthday }}{% endif %}</p>
          <p><b>Gender: </b> {% if person.gender %}{{ person.get_gender_display }}{% endif %}</p>
        </div>
      </div>
    </div>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow w-75 mx-auto">
    <div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-0">
      <h3>Films</h3>
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-actor-tab" data-bs-toggle="pill" data-bs-target="#pills-actor"
                  type="button" role="tab" aria-controls="pills-home" aria-selected="true">
            As Actor
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-director-tab" data-bs-toggle="pill" data-bs-target="#pills-director"
                  type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
            As Director
          </button>
        </li>
      </ul>
    </div>

    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-actor" role="tabpanel" aria-labelledby="pills-actor-tab">
        <div class="d-grid gap-3 mt-3">
          {% include 'cinema/film_list.html' with films=actor_films only%}
        </div>
      </div>
      <div class="tab-pane fade" id="pills-director" role="tabpanel" aria-labelledby="pills-director-tab">
        <div class="d-grid gap-3 mt-3">
          {% include 'cinema/film_list.html' with films=director_films only%}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/cinema/person_list.html
{% load static thumbnail %}

{% for person in person_list %}
  <div class="col col-sm-6 col-lg-4 mb-4">
    <div class="card border-dark text-center shadow h-100">
      <div class="bg-image hover-zoom">
        {% if person.image %}
          {% thumbnail person.image 250x250 crop="100%" as im %}
          <img src="{{ im.url }}" class="card-img-top ">
        {% else %}
          <img src="{% static "images/man_question.png" %}" class="card-top">
        {% endif %}
      </div>
      <div class="card-body">
        <a href="{% url "cinema:person_detail" person.id %}" class="link-dark">
          <h5 class="card-title">{{ person.name }}</h5>
        </a>
      </div>
    </div>
  </div>
{% endfor %}

templates/cinema/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Search results{% endblock title %}

{% block content %}
  <div class="my-3 p-3 w-75 mx-auto">
    <div class="d-flex bg-dark justify-content-between align-items-center mb-2 text-white rounded">
      <p><h3 class="my-1">Search Results</h3></p>
    </div>
    
    <div id="films-list" class="d-grid gap-1 ">
      {% include 'cinema/film_list.html' with films=films only%}
    </div>
    <div id="actor-director-list" class="row row-cols-1 row-cols-md-3 mt-2">
      {% include 'cinema/person_list.html' with person_list=people only %}
    </div>

  </div>
{% endblock content %}