account/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetView,
)
from django.urls import include, path, reverse_lazy

from . import views

app_name = "account"
urlpatterns = [
    path(route="signup/", view=views.user_signup_view, name="signup"),
    path(route="profile/", view=views.user_profile_view, name="profile"),
    path(
        route="password_reset/",
        view=PasswordResetView.as_view(
            success_url=reverse_lazy("account:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        route="reset/<uidb64>/<token>/",
        view=PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("account:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path("", include("django.contrib.auth.urls")),
]

cinema/urls.py
from django.urls import path

from cinema import views

app_name = "cinema"
urlpatterns = [
    path(route="", view=views.film_list_view, name="film_list"),
    path(
        route="search/",
        view=views.search_view,
        name="search",
    ),
    path(
        route="<slug:genre_slug>/",
        view=views.film_list_view,
        name="film_list_by_genre",
    ),
    path(
        route="films/<slug:slug>/",
        view=views.film_detail_view,
        name="film_detail",
    ),
    path(
        route="people/<person_role>/",
        view=views.people_list_view,
        name="people_list",
    ),
    path(
        route="person/<int:person_id>",
        view=views.person_detail_view,
        name="person_detail",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("accounts/", include("account.urls")),
    path("api/v1/", include("api.urls")),
    path("", include("cinema.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>

  <link rel="stylesheet" href="{% static 'css/stylesheet.css'%}" type="text/css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
  
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <header class="sticky-top">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Course Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-0 mb-lg-0">
            <li class="nav-item" >
              <a class="nav-link" href="{% url "cinema:film_list" %}">Movies</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "cinema:people_list" "actors" %}">Actors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "cinema:people_list" "directors" %}">Directors</a>
            </li>
            {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
              </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                  data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="{% url "account:profile" %}">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url "account:logout" %}">Log out</a></li>
                {% else %}
                  <li><a class="dropdown-item" href="{% url "account:signup" %}">Sign Up</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url "account:login" %}">Log in</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
          <form class="d-flex" action="{% url "cinema:search" %}" method="get">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_line">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

  <div class="container">
    {% block content %}{% endblock content %}
  </div>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
        {% block domready %}
        {% endblock %}
    });
   </script>
</body>
</html>